class_name MOVES

enum moves{LIGHTATTACK,HEAVYATTACK,WALKFORWARD,WALKBACKWARD,BLOCK,JUMP,JUMPFORWARD,JUMPBACKWARD,IDLE,RECOVER,SPECIAL}
enum moveInputs{LIGHTATTACK,HEAVYATTACK,WALKLEFT,WALKRIGHT,BLOCK,JUMP}
enum moveTypes{ATTACK,WALK,JUMP,BLOCK}
