class_name MOVES

enum moves{LIGHTATTACK,HEAVYATTACK,WALKFORWARD,WALKBACKWARD,BLOCK,JUMP,JUMPFORWARD,JUMPBACKWARD,IDLE,RECOVER,HURT,SPECIAL,ENTRANCE,DEATH,WIN,TEST}
enum moveInputs{LIGHTATTACK,HEAVYATTACK,WALKLEFT,WALKRIGHT,BLOCK,JUMP,TEST}
enum moveTypes{ATTACK,WALK,JUMP,BLOCK}
